// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace NinjaManager.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PROG5.Data.Models.Gear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Category")
                        .IsUnique();

                    b.ToTable("Gears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 100,
                            Category = 0,
                            Gold = 50,
                            Intelligence = 10,
                            Name = "Iron Helmet",
                            Strength = 10
                        },
                        new
                        {
                            Id = 2,
                            Agility = 50,
                            Category = 0,
                            Gold = 75,
                            Intelligence = 50,
                            Name = "Gold Helmet",
                            Strength = 50
                        },
                        new
                        {
                            Id = 3,
                            Agility = 10,
                            Category = 0,
                            Gold = 100,
                            Intelligence = 100,
                            Name = "Diamond Helmet",
                            Strength = 100
                        },
                        new
                        {
                            Id = 4,
                            Agility = 100,
                            Category = 5,
                            Gold = 50,
                            Intelligence = 10,
                            Name = "Iron Necklace",
                            Strength = 10
                        },
                        new
                        {
                            Id = 5,
                            Agility = 50,
                            Category = 5,
                            Gold = 75,
                            Intelligence = 50,
                            Name = "Gold Necklace",
                            Strength = 50
                        },
                        new
                        {
                            Id = 6,
                            Agility = 10,
                            Category = 5,
                            Gold = 100,
                            Intelligence = 100,
                            Name = "Diamond Necklace",
                            Strength = 100
                        },
                        new
                        {
                            Id = 7,
                            Agility = 100,
                            Category = 1,
                            Gold = 50,
                            Intelligence = 10,
                            Name = "Iron Chest",
                            Strength = 10
                        },
                        new
                        {
                            Id = 8,
                            Agility = 50,
                            Category = 1,
                            Gold = 75,
                            Intelligence = 50,
                            Name = "Gold Chest",
                            Strength = 50
                        },
                        new
                        {
                            Id = 9,
                            Agility = 10,
                            Category = 1,
                            Gold = 100,
                            Intelligence = 100,
                            Name = "Diamond Chest",
                            Strength = 100
                        },
                        new
                        {
                            Id = 10,
                            Agility = 100,
                            Category = 2,
                            Gold = 50,
                            Intelligence = 10,
                            Name = "Iron Gloves",
                            Strength = 10
                        },
                        new
                        {
                            Id = 11,
                            Agility = 50,
                            Category = 2,
                            Gold = 75,
                            Intelligence = 50,
                            Name = "Gold Gloves",
                            Strength = 50
                        },
                        new
                        {
                            Id = 12,
                            Agility = 10,
                            Category = 2,
                            Gold = 100,
                            Intelligence = 100,
                            Name = "Diamond Gloves",
                            Strength = 100
                        },
                        new
                        {
                            Id = 13,
                            Agility = 100,
                            Category = 4,
                            Gold = 50,
                            Intelligence = 10,
                            Name = "Iron Ring",
                            Strength = 10
                        },
                        new
                        {
                            Id = 14,
                            Agility = 50,
                            Category = 4,
                            Gold = 75,
                            Intelligence = 50,
                            Name = "Gold Ring",
                            Strength = 50
                        },
                        new
                        {
                            Id = 15,
                            Agility = 10,
                            Category = 4,
                            Gold = 100,
                            Intelligence = 100,
                            Name = "Diamond Ring",
                            Strength = 100
                        },
                        new
                        {
                            Id = 16,
                            Agility = 100,
                            Category = 3,
                            Gold = 50,
                            Intelligence = 10,
                            Name = "Iron Boots",
                            Strength = 10
                        },
                        new
                        {
                            Id = 17,
                            Agility = 50,
                            Category = 3,
                            Gold = 75,
                            Intelligence = 50,
                            Name = "Gold Boots",
                            Strength = 50
                        },
                        new
                        {
                            Id = 18,
                            Agility = 10,
                            Category = 3,
                            Gold = 100,
                            Intelligence = 100,
                            Name = "Diamond Boots",
                            Strength = 100
                        });
                });

            modelBuilder.Entity("PROG5.Data.Models.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gold = 600,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Gold = 275,
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("PROG5.Data.Models.NinjaGear", b =>
                {
                    b.Property<int>("NinjaId")
                        .HasColumnType("int");

                    b.Property<int>("GearId")
                        .HasColumnType("int");

                    b.HasKey("NinjaId", "GearId");

                    b.HasIndex("GearId");

                    b.ToTable("NinjaGear");
                });

            modelBuilder.Entity("PROG5.Data.Models.NinjaGear", b =>
                {
                    b.HasOne("PROG5.Data.Models.Gear", "Gear")
                        .WithMany("NinjaGears")
                        .HasForeignKey("GearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROG5.Data.Models.Ninja", "Ninja")
                        .WithMany("NinjaGears")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
